{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\sklearn\\ensemble\\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.\n",
      "  from numpy.core.umath_tests import inner1d\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "article 27953647  not found.\n",
      "article 27948541  not found.\n",
      "article 27943881  not found.\n",
      "article 27949797  not found.\n",
      "article 27955116  not found.\n",
      "article 27950623  not found.\n",
      "article 27945102  not found.\n",
      "clinical trial NCT02659670  not found.\n",
      "article 27198327  not found.\n"
     ]
    }
   ],
   "source": [
    "import articles.article_fetch as article_fetch\n",
    "import articles.articles_info as article_info\n",
    "from articles import article\n",
    "\n",
    "import csv\n",
    "import codecs\n",
    "\n",
    "import pandas as pd\n",
    "from classifiers.random_forest import RandomForest\n",
    "from classifiers.svm_classifier import SVMClassifier\n",
    "from classifiers.mlp_classifier import MLPClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import confusion_matrix, classification_report\n",
    "from sklearn.metrics import precision_recall_fscore_support\n",
    "\n",
    "import clinical_trials.clinical_trial_fetch as ct_fetch\n",
    "import clinical_trials.clinical_trials_info as ct_info\n",
    "from clinical_trials import clinical_trial\n",
    "\n",
    "import csv\n",
    "import csv_data.csv as csv_data\n",
    "\n",
    "from dataframe import create_dataframe\n",
    "from dataframe import calculate_attributes\n",
    "\n",
    "from common_functions import common_functions\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "import importlib\n",
    "\n",
    "# I get the gold standard\n",
    "gold_standard = pd.read_csv('ClinicalPmidsALL.csv', encoding = 'ISO-8859-1', sep = ';')\n",
    "\n",
    "# Now I change the common answer from string to numerical\n",
    "csv_data.numerical_answers(gold_standard)\n",
    "\n",
    "# Let's correct data on csv (common answer sometimes is not correct)\n",
    "csv_data.correctData(gold_standard)\n",
    "\n",
    "# I get all the clinical trials ID and I get the articles in xml\n",
    "Clinical_trials = ct_fetch.get_xml_doms(gold_standard['CT'].tolist())\n",
    "\n",
    "# I get all the PMID and I get the articles in xml\n",
    "PubMed_id_string = list(map(str, gold_standard['PMID'].tolist())) # I get the PMID as list of strings\n",
    "PubMed_articles = article_fetch.fetch_many_articles(PubMed_id_string, local=True) # It takes time to fetch the articles\n",
    "\n",
    "# Let's map every clinical trial to every article (and remove the one that are not present) and common answer\n",
    "df = create_dataframe.get_base_dataframe(gold_standard, Clinical_trials, PubMed_articles)\n",
    "\n",
    "# standard, spacy or stanford\n",
    "ct_org_sample = 'standard'\n",
    "ar_org_sample = 'spacy'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#lam = gold_standard['CT']\n",
    "#lam.index[lam == 'NCT00003204'].tolist()[0]\n",
    "\n",
    "ct_last_names, ct_first_name_initials, ct_first_names = ct_info.get_all_name_parts(df['CT'].tolist(), gold_standard)\n",
    "\n",
    "df['ct_last_name'], df['ct_first_name_initial'], df['ct_first_name'] = [ct_last_names, ct_first_name_initials, ct_first_names]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# print(sum(x is not None for x in ct_last_names))\n",
    "df = df.dropna().reset_index(drop = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "ar_last_names, ar_first_name_initials, ar_first_names = article_info.get_all_name_parts(df['PubMed'].tolist(), gold_standard)\n",
    "\n",
    "df['ar_last_name'], df['ar_first_name_initial'], df['ar_first_name'] = [ar_last_names, ar_first_name_initials, ar_first_names]\n",
    "df.dropna().reset_index(drop = True)\n",
    "print()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "NCT00730210 doesn't have an organization.\n",
      "NCT02220283 doesn't have an organization.\n"
     ]
    }
   ],
   "source": [
    "# now that we have the base information, let's add other attributes\n",
    "\n",
    "# we get the organization of the principal investigator, so we don't need to pass his/her name\n",
    "ct_organization_names = ct_info.get_all_organization_names(df['CT'].tolist(), df['ct_last_name'].tolist(),\n",
    "                                                           df['ct_first_name_initial'].tolist(),\n",
    "                                                           sample=ct_org_sample)\n",
    "\n",
    "# Now we insert it in the dataframe\n",
    "if('ct_organization' not in df):\n",
    "    df.insert(6, 'ct_organization', ct_organization_names)\n",
    "    \n",
    "\n",
    "# I get the e-mails\n",
    "ct_mails = ct_info.get_all_mails(df['CT'].tolist(), df['ct_last_name'].tolist(), df['ct_first_name_initial'].tolist())\n",
    "\n",
    "if('ct_mail' not in df):\n",
    "    df.insert(7, 'ct_mail', ct_mails)\n",
    "    \n",
    "# I get the year\n",
    "ct_years = ct_info.get_all_years(df['CT'].tolist())\n",
    "    \n",
    "if('ct_year' not in df):\n",
    "    df.insert(8, 'ct_year', ct_years)\n",
    "    \n",
    "# I get the initials of the name\n",
    "ct_initials = ct_info.get_all_initials(df['ct_first_name'].tolist())\n",
    "\n",
    "if('ct_initials' not in df):\n",
    "    df.insert(9, 'ct_initials', ct_initials)\n",
    "    \n",
    "# I get the title\n",
    "ct_titles = ct_info.get_all_titles(df['CT'].tolist())\n",
    "\n",
    "if('ct_title' not in df):\n",
    "    df.insert(10, 'ct_title', ct_titles)\n",
    "    \n",
    "# I get the country and the city\n",
    "ct_countries, ct_cities = ct_info.get_all_countries_and_cities(df['CT'].tolist())\n",
    "\n",
    "if('ct_country' not in df):\n",
    "    df.insert(11, 'ct_country', ct_countries)\n",
    "    \n",
    "if('ct_city' not in df):\n",
    "    df.insert(12, 'ct_city', ct_cities)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "267\n"
     ]
    }
   ],
   "source": [
    "print(sum(x is not None for x in df['ct_mail']))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "475\n",
      "126\n"
     ]
    }
   ],
   "source": [
    "# Let's add the same attributes for the articles\n",
    "\n",
    "ar_organization_names, ar_locations = article_info.get_all_organizations_locations(df['PubMed'].tolist(),\n",
    "                                                           df['ar_last_name'].tolist(),\n",
    "                                                           df['ar_first_name_initial'].tolist(),\n",
    "                                                           sample = ar_org_sample)\n",
    "df['ar_organization'] = ar_organization_names\n",
    "\n",
    "ar_mails = article_info.get_all_mails(df['PubMed'].tolist(), df['ar_last_name'].tolist(),\n",
    "                                      df['ar_first_name_initial'].tolist())\n",
    "df['ar_mail'] = ar_mails\n",
    "\n",
    "ar_years = article_info.get_all_years(df['PubMed'].tolist())\n",
    "\n",
    "df['ar_year'] = ar_years\n",
    "\n",
    "ar_initials = article_info.get_all_initials(df['ar_first_name'])\n",
    "\n",
    "df['ar_initials'] = ar_initials\n",
    "\n",
    "ar_titles = article_info.get_all_titles(df['PubMed'].tolist())\n",
    "\n",
    "df['ar_title'] = ar_titles\n",
    "df['ar_location'] = ar_locations\n",
    "\n",
    "print(sum(x is not None for x in ar_organization_names))\n",
    "print(sum(x is not None for x in ar_mails))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# I now calculate useful attributes for the classifiers\n",
    "first_name_equalities = calculate_attributes.get_string_arrays_similarity(df['ct_first_name'].tolist(),\n",
    "                                                                          df['ar_first_name'].tolist())\n",
    "organization_similarities, organization_type_equalities = calculate_attributes.get_organization_similarity_and_type_equality(df['ct_organization'].tolist(),\n",
    "                                                                             df['ar_organization'].tolist(),\n",
    "                                                                             ct_org_sample, ar_org_sample)\n",
    "email_equalities = calculate_attributes.get_arrays_equality(df['ct_mail'].tolist(), df['ar_mail'].tolist())\n",
    "year_differences = calculate_attributes.get_year_differences(df['ct_year'].tolist(), df['ar_year'].tolist())\n",
    "last_name_lengths = calculate_attributes.get_last_name_lengths(df['ct_last_name'].tolist())\n",
    "initials_equality = calculate_attributes.get_arrays_equality(df['ct_initials'].tolist(), df['ar_initials'].tolist())\n",
    "namespace_sizes = calculate_attributes.get_namespace_ambiguities(df['ct_last_name'].tolist(),\n",
    "                                                                 df['ct_first_name_initial'].tolist())\n",
    "country_equalities, city_equalities = calculate_attributes.get_location_equalities(df['ct_country'].tolist(),\n",
    "                                                                                   df['ct_city'].tolist(),\n",
    "                                                                                   df['ar_location'].tolist())\n",
    "\n",
    "# Let's add the attributes to the data frame\n",
    "df['first_name_equality'], df['organization_similarity'] = [first_name_equalities, organization_similarities]\n",
    "df['email_equality'], df['year_difference'] = [email_equalities, year_differences]\n",
    "df['last_name_length'], df['initials_equality'] = [last_name_lengths, initials_equality]\n",
    "df['namespace_size'], df ['country_equality'] = [namespace_sizes, country_equalities]\n",
    "df['city_equality'], df['organization_type_equality'] = [city_equalities, organization_type_equalities]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from java_libraries import java_server\n",
    "\n",
    "clinical_trials = df['CT'].tolist()\n",
    "articles = df['PubMed'].tolist()\n",
    "\n",
    "server = java_server.JavaServer()\n",
    "\n",
    "jds = []\n",
    "sts = []\n",
    "for i in range(len(articles)):\n",
    "    ct_texts = clinical_trials[i].get_text()\n",
    "    ct_texts.append(clinical_trials[i].get_title())\n",
    "    ct_texts = \" \".join(ct_texts)\n",
    "\n",
    "    ar_texts = articles[i].get_text()\n",
    "    ar_texts.append(articles[i].get_title())\n",
    "    ar_texts = \" \".join(ar_texts)\n",
    "        \n",
    "    jd = [server.get_jds(ct_texts), server.get_jds(ar_texts)]\n",
    "    jds.append(jd)\n",
    "    st = [server.get_sts(ct_texts), server.get_sts(ar_texts)]\n",
    "    sts.append(st)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "server.close_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "from dataframe import calculate_attributes\n",
    "\n",
    "for i in range(1,100):\n",
    "    sts_similarities = []\n",
    "    for j in range(len(sts)):\n",
    "        sts_similarities.append(calculate_attributes.get_jds_sts_basic_similarities(sts[j][0][:i],sts[j][1][:i]))\n",
    "    \n",
    "    df['sts_similarity'] = sts_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "for i in range(1,100):\n",
    "    sts_similarities = []\n",
    "    for j in range(len(sts)):\n",
    "        sts_similarities.append(calculate_attributes.get_jds_sts_percentage_similarities(sts[j][0][:i],sts[j][1][:i]))\n",
    "    \n",
    "    df['sts_similarity'] = sts_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "max_precision = 0\n",
    "\n",
    "for i in range(1,100):\n",
    "    sts_similarities = []\n",
    "    for j in range(len(sts)):\n",
    "        sts_similarities.append(calculate_attributes.get_jds_sts_ranking_similarities(sts[j][0][:i],sts[j][1][:i]))\n",
    "    \n",
    "    df['sts_similarity'] = sts_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1174, in send_command\n",
      "    self.socket.sendall(command.encode(\"utf-8\"))\n",
      "ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1014, in send_command\n",
      "    response = connection.send_command(command)\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1178, in send_command\n",
      "    \"Error while sending\", e, proto.ERROR_ON_SEND)\n",
      "py4j.protocol.Py4JNetworkError: Error while sending\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "i: 1 average precision: 0.8571297019050473\n",
      "i: 2 average precision: 0.868906182064092\n",
      "i: 3 average precision: 0.8689609486043117\n",
      "i: 4 average precision: 0.870219125047671\n",
      "i: 5 average precision: 0.8757597142434291\n",
      "i: 6 average precision: 0.8773593346679308\n",
      "i: 7 average precision: 0.8768117219214954\n",
      "i: 8 average precision: 0.8775081715071468\n",
      "i: 9 average precision: 0.8793697772382183\n",
      "i: 10 average precision: 0.8803647470918708\n",
      "i: 11 average precision: 0.8788165918668426\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:25333)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 958, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Brescia\\Anaconda3\\lib\\site-packages\\py4j\\java_gateway.py\", line 1096, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [WinError 10061] Impossibile stabilire la connessione. Rifiuto persistente del computer di destinazione\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "i: 12 average precision: 0.8798129095896039\n",
      "i: 13 average precision: 0.8782264412706732\n",
      "i: 14 average precision: 0.8801505880049666\n",
      "i: 15 average precision: 0.8796300083874733\n",
      "i: 16 average precision: 0.8793904855285172\n",
      "i: 17 average precision: 0.8794937947871546\n",
      "i: 18 average precision: 0.8792867836161199\n",
      "i: 19 average precision: 0.8803383146411174\n",
      "i: 20 average precision: 0.8794371228808333\n",
      "i: 21 average precision: 0.8788474684390007\n",
      "i: 22 average precision: 0.8794974109620359\n",
      "i: 23 average precision: 0.8798781998637325\n",
      "i: 24 average precision: 0.8802518927569877\n",
      "i: 25 average precision: 0.8797412145960658\n",
      "i: 26 average precision: 0.8806437748851167\n",
      "i: 27 average precision: 0.8809018931996451\n",
      "i: 28 average precision: 0.8806257021130687\n",
      "i: 29 average precision: 0.8796036246533094\n",
      "i: 30 average precision: 0.8794927936569963\n",
      "i: 31 average precision: 0.879474816027913\n",
      "i: 32 average precision: 0.8790976581588353\n",
      "i: 33 average precision: 0.8791435757334114\n",
      "i: 34 average precision: 0.8800394954243669\n",
      "i: 35 average precision: 0.8797368743309175\n",
      "i: 36 average precision: 0.8799770992302258\n",
      "i: 37 average precision: 0.8798155075277272\n",
      "i: 38 average precision: 0.8791408125406648\n",
      "i: 39 average precision: 0.878803472228509\n",
      "i: 40 average precision: 0.8794325399034846\n",
      "i: 41 average precision: 0.8797365658138752\n",
      "i: 42 average precision: 0.8797393609529968\n",
      "i: 43 average precision: 0.8792616253990951\n",
      "i: 44 average precision: 0.8795736877578567\n",
      "i: 45 average precision: 0.8804599555643687\n",
      "i: 46 average precision: 0.88042714648777\n",
      "i: 47 average precision: 0.8799471323090802\n",
      "i: 48 average precision: 0.8802147581989669\n",
      "i: 49 average precision: 0.879836567495626\n",
      "i: 50 average precision: 0.8803428717775987\n",
      "i: 51 average precision: 0.8804355763815113\n",
      "i: 52 average precision: 0.8810977796769192\n",
      "i: 53 average precision: 0.8806396120848948\n",
      "i: 54 average precision: 0.8800846113448249\n",
      "i: 55 average precision: 0.8798682285053868\n",
      "i: 56 average precision: 0.879760800984997\n",
      "i: 57 average precision: 0.8799113029080339\n",
      "i: 58 average precision: 0.8802536013742214\n",
      "i: 59 average precision: 0.8800907433216126\n",
      "i: 60 average precision: 0.8804722855465341\n",
      "i: 61 average precision: 0.8804157672312672\n",
      "i: 62 average precision: 0.8801425265745081\n",
      "i: 63 average precision: 0.8797082479785403\n",
      "i: 64 average precision: 0.8808123680176856\n",
      "i: 65 average precision: 0.8804138329375641\n",
      "i: 66 average precision: 0.8801215106542191\n",
      "i: 67 average precision: 0.8793796373509992\n",
      "i: 68 average precision: 0.8795816121099181\n",
      "i: 69 average precision: 0.8797132941307182\n",
      "i: 70 average precision: 0.879061067814026\n",
      "i: 71 average precision: 0.8794313900375514\n",
      "i: 72 average precision: 0.8792702529617009\n",
      "i: 73 average precision: 0.8788699149215303\n",
      "i: 74 average precision: 0.8790083205614002\n",
      "i: 75 average precision: 0.8792664519719443\n",
      "i: 76 average precision: 0.8793478745551832\n",
      "i: 77 average precision: 0.8790926595169138\n",
      "i: 78 average precision: 0.8793196285058253\n",
      "i: 79 average precision: 0.8787841835230968\n",
      "i: 80 average precision: 0.8793467111408938\n",
      "i: 81 average precision: 0.8790681557490769\n",
      "i: 82 average precision: 0.8792040465932058\n",
      "i: 83 average precision: 0.8791346991033538\n",
      "i: 84 average precision: 0.8793073366778927\n",
      "i: 85 average precision: 0.878758337792404\n",
      "i: 86 average precision: 0.87928593054988\n",
      "i: 87 average precision: 0.8790976162675264\n",
      "i: 88 average precision: 0.8790522713133972\n",
      "i: 89 average precision: 0.879134787030474\n",
      "i: 90 average precision: 0.8792434885115727\n",
      "i: 91 average precision: 0.8791148886437478\n",
      "i: 92 average precision: 0.8789019874723546\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-11-810d2a1995a8>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     32\u001b[0m         \u001b[0mx_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mx_test\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_test\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtrain_test_split\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtest_size\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m0.33\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrandom_state\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     33\u001b[0m         \u001b[0mclassifier\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mRandomForest\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 34\u001b[1;33m         \u001b[0mclassifier\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcreate_model\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     35\u001b[0m         \u001b[0mpred\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mclassifier\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpredict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx_test\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     36\u001b[0m         \u001b[0mavg_precision\u001b[0m \u001b[1;33m+=\u001b[0m \u001b[0mprecision_recall_fscore_support\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my_test\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpred\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maverage\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'weighted'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\Diploma\\classifiers\\random_forest.py\u001b[0m in \u001b[0;36mcreate_model\u001b[1;34m(self, x_train, y_train)\u001b[0m\n\u001b[0;32m     14\u001b[0m         self.rfc = RandomForestClassifier(random_state=self.random_state, n_estimators=500, max_depth=None,\n\u001b[0;32m     15\u001b[0m                                           min_samples_split=2, max_features='auto')\n\u001b[1;32m---> 16\u001b[1;33m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mrfc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mx_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     17\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mcanSave\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;32mTrue\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     18\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\ensemble\\forest.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, sample_weight)\u001b[0m\n\u001b[0;32m    314\u001b[0m             \u001b[1;32mfor\u001b[0m \u001b[0mi\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mn_more_estimators\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    315\u001b[0m                 tree = self._make_estimator(append=False,\n\u001b[1;32m--> 316\u001b[1;33m                                             random_state=random_state)\n\u001b[0m\u001b[0;32m    317\u001b[0m                 \u001b[0mtrees\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtree\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    318\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\ensemble\\base.py\u001b[0m in \u001b[0;36m_make_estimator\u001b[1;34m(self, append, random_state)\u001b[0m\n\u001b[0;32m    128\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    129\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mrandom_state\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 130\u001b[1;33m             \u001b[0m_set_random_states\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mestimator\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    131\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    132\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mappend\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\ensemble\\base.py\u001b[0m in \u001b[0;36m_set_random_states\u001b[1;34m(estimator, random_state)\u001b[0m\n\u001b[0;32m     55\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     56\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mto_set\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 57\u001b[1;33m         \u001b[0mestimator\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mset_params\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mto_set\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     58\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     59\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36mset_params\u001b[1;34m(self, **params)\u001b[0m\n\u001b[0;32m    263\u001b[0m             \u001b[1;31m# Simple optimization to gain speed (inspect is slow)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    264\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 265\u001b[1;33m         \u001b[0mvalid_params\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_params\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdeep\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    266\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    267\u001b[0m         \u001b[0mnested_params\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdefaultdict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdict\u001b[0m\u001b[1;33m)\u001b[0m  \u001b[1;31m# grouped by prefix\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36mget_params\u001b[1;34m(self, deep)\u001b[0m\n\u001b[0;32m    226\u001b[0m         \"\"\"\n\u001b[0;32m    227\u001b[0m         \u001b[0mout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mdict\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 228\u001b[1;33m         \u001b[1;32mfor\u001b[0m \u001b[0mkey\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_get_param_names\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    229\u001b[0m             \u001b[1;31m# We need deprecation warnings to always be on in order to\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    230\u001b[0m             \u001b[1;31m# catch deprecated param values.\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36m_get_param_names\u001b[1;34m(cls)\u001b[0m\n\u001b[0;32m    196\u001b[0m         \u001b[1;31m# introspect the constructor arguments to find the model parameters\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    197\u001b[0m         \u001b[1;31m# to represent\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 198\u001b[1;33m         \u001b[0minit_signature\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0msignature\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minit\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    199\u001b[0m         \u001b[1;31m# Consider the constructor parameters excluding 'self'\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    200\u001b[0m         parameters = [p for p in init_signature.parameters.values()\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36msignature\u001b[1;34m(obj, follow_wrapped)\u001b[0m\n\u001b[0;32m   3050\u001b[0m \u001b[1;32mdef\u001b[0m \u001b[0msignature\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m*\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfollow_wrapped\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3051\u001b[0m     \u001b[1;34m\"\"\"Get a signature object for the passed callable.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 3052\u001b[1;33m     \u001b[1;32mreturn\u001b[0m \u001b[0mSignature\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfrom_callable\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfollow_wrapped\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mfollow_wrapped\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   3053\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   3054\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36mfrom_callable\u001b[1;34m(cls, obj, follow_wrapped)\u001b[0m\n\u001b[0;32m   2800\u001b[0m         \u001b[1;34m\"\"\"Constructs Signature for the given callable object.\"\"\"\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2801\u001b[0m         return _signature_from_callable(obj, sigcls=cls,\n\u001b[1;32m-> 2802\u001b[1;33m                                         follow_wrapper_chains=follow_wrapped)\n\u001b[0m\u001b[0;32m   2803\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2804\u001b[0m     \u001b[1;33m@\u001b[0m\u001b[0mproperty\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36m_signature_from_callable\u001b[1;34m(obj, follow_wrapper_chains, skip_bound_arg, sigcls)\u001b[0m\n\u001b[0;32m   2260\u001b[0m         \u001b[1;31m# If it's a pure Python function, or an object that is duck type\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2261\u001b[0m         \u001b[1;31m# of a Python function (Cython functions, for instance), then:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2262\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0m_signature_from_function\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msigcls\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2263\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2264\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0m_signature_is_builtin\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mobj\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36m_signature_from_function\u001b[1;34m(cls, func)\u001b[0m\n\u001b[0;32m   2171\u001b[0m     return cls(parameters,\n\u001b[0;32m   2172\u001b[0m                \u001b[0mreturn_annotation\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mannotations\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'return'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0m_empty\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2173\u001b[1;33m                __validate_parameters__=is_duck_function)\n\u001b[0m\u001b[0;32m   2174\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2175\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, parameters, return_annotation, __validate_parameters__)\u001b[0m\n\u001b[0;32m   2773\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2774\u001b[0m                 params = OrderedDict(((param.name, param)\n\u001b[1;32m-> 2775\u001b[1;33m                                                 for param in parameters))\n\u001b[0m\u001b[0;32m   2776\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2777\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_parameters\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtypes\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mMappingProxyType\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36m<genexpr>\u001b[1;34m(.0)\u001b[0m\n\u001b[0;32m   2773\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2774\u001b[0m                 params = OrderedDict(((param.name, param)\n\u001b[1;32m-> 2775\u001b[1;33m                                                 for param in parameters))\n\u001b[0m\u001b[0;32m   2776\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2777\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_parameters\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtypes\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mMappingProxyType\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\Anaconda3\\lib\\inspect.py\u001b[0m in \u001b[0;36mname\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   2493\u001b[0m         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_annotation\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mstate\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;34m'_annotation'\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2494\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2495\u001b[1;33m     \u001b[1;33m@\u001b[0m\u001b[0mproperty\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   2496\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mname\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2497\u001b[0m         \u001b[1;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_name\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "max_precision = 0\n",
    "\n",
    "for i in range(1,100):\n",
    "    sts_similarities = []\n",
    "    for j in range(len(sts)):\n",
    "        sts_similarities.append(calculate_attributes.get_jds_sts_percentage_ranking_similarities(sts[j][0][:i],sts[j][1][:i]))\n",
    "    \n",
    "    df['sts_similarity'] = sts_similarities\n",
    "\n",
    "    # normalize\n",
    "    df['namespace_size'] = common_functions.normalize(df['namespace_size'])\n",
    "    df['last_name_length'] = common_functions.normalize(df['last_name_length'])\n",
    "    df['year_difference'] = common_functions.normalize(df['year_difference'])\n",
    "\n",
    "    # save csv\n",
    "    df_to_save = df.drop(['CT', 'PubMed', 'ct_last_name', 'ct_first_name_initial', 'ct_first_name',\n",
    "          'ct_organization', 'ct_mail', 'ct_year', 'ct_initials', 'ct_title', 'ct_country', 'ct_city', \n",
    "            'ar_last_name','ar_first_name_initial','ar_first_name','ar_organization', 'ar_mail', 'ar_initials',\n",
    "                  'ar_year', 'ar_title', 'ar_location'], axis = 1)\n",
    "    csv = df_to_save.to_csv(index=False)\n",
    "    file = codecs.open(\"dataframe.csv\", \"w\", \"utf-8\")\n",
    "    file.write(csv)\n",
    "    file.close()\n",
    "\n",
    "    # model\n",
    "    df_model = pd.read_csv('dataframe.csv', encoding = 'utf-8')\n",
    "    x = df_model.drop('common_answer', axis=1)\n",
    "    y = df_model['common_answer']\n",
    "\n",
    "    avg_precision = 0\n",
    "    for k in range(100):\n",
    "        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33, random_state = k)\n",
    "        classifier = RandomForest(0)\n",
    "        classifier.create_model(x_train, y_train)\n",
    "        pred = classifier.predict(x_test)\n",
    "        avg_precision += precision_recall_fscore_support(y_test, pred, average='weighted')[0]\n",
    "    avg_precision /= 100\n",
    "\n",
    "    print(\"i:\",i,\"average precision:\",avg_precision)\n",
    "\n",
    "    if avg_precision > max_precision:\n",
    "        max_precision = avg_precision\n",
    "        best_i = i\n",
    "        \n",
    "print(best_i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "importlib.reload(article_info)\n",
    "importlib.reload(ct_info)\n",
    "importlib.reload(calculate_attributes)\n",
    "importlib.reload(clinical_trial)\n",
    "importlib.reload(common_functions)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
